/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.example;

import static org.junit.Assert.assertNotNull;

import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    
    @Test
    public void test_the_running_app_just_for_code_coverage() throws Exception{
        //inicia la app y levanta todos los files de las configuraciones
        String[] args = {""};
        App.main(args);        
    }
       
}
